# Generated by Django 3.2 on 2022-02-28 05:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(default='ad'),
            preserve_default=False,
        ),
    ]
