# Generated by Django 3.2 on 2022-03-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coverVideo',
            new_name='video',
        ),
    ]
