# Generated by Django 3.2 on 2022-03-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_covervideo_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
