# Generated by Django 3.2 on 2022-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_savepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='savepost',
            name='key',
            field=models.CharField(max_length=150),
        ),
    ]
