# Generated by Django 3.2 on 2022-03-06 04:30

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('dateTimeSubmit', models.DateTimeField(auto_now=True)),
                ('imageProfile', models.URLField(default=Blog.models.RandomSrcImage)),
            ],
        ),
    ]
