# Generated by Django 3.2 on 2022-03-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
