# Generated by Django 3.2 on 2022-03-06 06:26

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_auto_20220306_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='imageProfile',
            field=models.CharField(default=Blog.models.RandomSrcImage, max_length=70),
        ),
    ]
